//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyQuizAttemptDetail
    {
        public int AttemptDetailId { get; set; }
        public Nullable<int> AttemptId { get; set; }
        public Nullable<int> DailyQuizCourseId { get; set; }
        public Nullable<int> DailyQuizSubjectId { get; set; }
        public Nullable<int> QuizTestId { get; set; }
        public int QuestionNumber { get; set; }
        public Nullable<int> QuizQuestionAnswerChoiceId { get; set; }
        public Nullable<int> AnswerChoiceId { get; set; }
        public string AnswerStatus { get; set; }
        public decimal MarksScored { get; set; }
        public bool IsAnswerCorrect { get; set; }
    
        public virtual DailyQuizAttempt DailyQuizAttempt { get; set; }
        public virtual DailyQuizCourse DailyQuizCourse { get; set; }
        public virtual DailyQuizSubject DailyQuizSubject { get; set; }
        public virtual QuizQuestionAnswerChoice QuizQuestionAnswerChoice { get; set; }
        public virtual QuizTest QuizTest { get; set; }
    }
}
