//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyQuizUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyQuizUpload()
        {
            this.QuizTests = new HashSet<QuizTest>();
        }
    
        public int DailyQuizUploadId { get; set; }
        public bool Isactive { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditOn { get; set; }
        public Nullable<int> DailyQuizCourseId { get; set; }
        public Nullable<int> DailyQuizSubjectId { get; set; }
        public Nullable<int> DataFileId { get; set; }
        public Nullable<int> DailyQuizId { get; set; }
        public string LanguageCode { get; set; }
        public string QuestionStatus { get; set; }
    
        public virtual DailyQuizCourse DailyQuizCourse { get; set; }
        public virtual DailyQuizSubject DailyQuizSubject { get; set; }
        public virtual DataFile DataFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizTest> QuizTests { get; set; }
        public virtual DailyQuiz DailyQuiz { get; set; }
    }
}
