//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockTestAttemptDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MockTestAttemptDetail()
        {
            this.ProblemsReporteds = new HashSet<ProblemsReported>();
        }
    
        public int AttemptDetailId { get; set; }
        public Nullable<int> AttemptId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> QuestionsMockTestId { get; set; }
        public int QuestionNumber { get; set; }
        public Nullable<int> ChoosenAnswerChoiceId { get; set; }
        public Nullable<int> AnswerChoiceId { get; set; }
        public string AnswerStatus { get; set; }
        public decimal MarksScored { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Course Course { get; set; }
        public virtual MockTestAttempt MockTestAttempt { get; set; }
        public virtual QuestionAnswerChoice QuestionAnswerChoice { get; set; }
        public virtual QuestionsMockTest QuestionsMockTest { get; set; }
        public virtual Section Section { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProblemsReported> ProblemsReporteds { get; set; }
    }
}
