//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswerChoice
    {
        public int QuestionAnswerChoiceId { get; set; }
        public string QuestionAnswer { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<int> QuestionsMockTestId { get; set; }
    
        public virtual QuestionsMockTest QuestionsMockTest { get; set; }
    }
}
