//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestionPoint
    {
        public int QuizQuestionPointId { get; set; }
        public string QuizQPoint { get; set; }
        public Nullable<int> QuizTestId { get; set; }
    
        public virtual QuizTest QuizTest { get; set; }
    }
}
