//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMasterG.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string type { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
    }
}
